export const REQUEST_COUNTRY = "REQUEST_COUNTRY";
export const SUCCESS_COUNTRY = "SUCCESS_COUNTRY";
export const FAILED_COUNTRY = "FAILED_COUNTRY";

export const REQUEST_STATE = "REQUEST_STATE";
export const SUCCESS_STATE = "SUCCESS_STATE";
export const FAILED_STATE = "FAILED_STATE";

export const REQUEST_CITY = "REQUEST_CITY";
export const SUCCESS_CITY = "SUCCESS_CITY";
export const FAILED_CITY = "FAILED_CITY";


export const REQUEST_ADD_PRODUCT = "REQUEST_ADD_PRODUCT";
export const SUCCESS_ADD_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILED_ADD_PRODUCT = "FAILED_ADD_PRODUCT";


export const REQUEST_GET_PRODUCT = "REQUEST_GET_PRODUCT";
export const SUCCESS_GET_PRODUCT = "SUCCESS_GET_PRODUCT";
export const FAILED_GET_PRODUCT = "FAILED_GET_PRODUCT";


export const REQUEST_GET_PRODUCT_BY_ID = "REQUEST_GET_PRODUCT_BY_ID";
export const SUCCESS_GET_PRODUCT_BY_ID = "SUCCESS_GET_PRODUCT_BY_ID";
export const FAILED_GET_PRODUCT_BY_ID = "FAILED_GET_PRODUCT_BY_ID";
